version: '3.8'

services:
  chroma-db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - ./chroma-data:/chroma/.chroma/index
    restart: unless-stopped
